meta_product_name: "Linen Chrome Extension"
meta_title: "Linen Chrome Extension - Get the best informations to guide your clothing purchases"
meta_description: "Linen is the best Chrome Extension providing trusted ethical ratings for online clothing purchases. Find the brands that match your values."
meta_image: "cover.jpg"
twitter_account: "@VictorLeboda"   # required for Twitter Cards, change with product account
